### ISSUE TITLE
mocksshy and command validation

### ISSUE THREAD

**Issue by mpenning** [ncouture/MockSSH#10]
I'm trying to build a hy-based test fixture, but I'm hitting a wall when it comes to command validation... this is my script:

    #!/usr/bin/env hy

    ; A mocked-up Cisco Router to test SSH connections

    (import MockSSH)
    (require mocksshy.language)

    (def *crlf* "\r\n")
    (def *MockHostname* "MockRouter")
    (def *MockPrompt1* (+ *MockHostname* ">"))
    (def *MockPrompt15* (+ *MockHostname* "#"))
    (def *MockConfPrompt* (+ *MockHostname* "(config)" "#"))
    (def *MockConfIntfPrompt* (+ *MockHostname* "(config-if)" "#"))
    (def *SyntaxError* (+ "           ^" *crlf* "% Invalid input detected at '^' marker." *crlf*))
    (def *AccessDenied* (+ "% Access denied" *crlf*))
    (def *ConfigMessage* (+ "Enter configuration commands, one per line.  End with CNTL/Z." *crlf*))

    (mock-ssh :users {"admin" "cisco"}
              :host "127.0.0.1"
              :port 2222
              :prompt *MockPrompt1*
              :commands [
      (command :name "enable"
               :type "prompt"
               :output "Password: "
               :required-input "cisco123"
               :on-success ["prompt" *MockPrompt15*]
               :on-failure ["write" *AccessDenied*])
      (command :name "term"
               :type "output"
               :args ["len 0"]
               :on-success ["prompt" *MockPrompt15*]
               :on-failure ["write" *SyntaxError*])])

The problem is no matter what I type for ``term ...``, the session gladly accepts it.  Using the example above...

    (py27_test)[mpenning@tsunami src]$ ssh -p 2222 admin@localhost
    admin@localhost's password:
    MockRouter>term len guacamole
    MockRouter>term
    MockRouter>t
    MockSSH: t: command not found
    MockRouter>

I wanted the script to require a literal ``term len 0``; however, it takes anything.  Is this expected behavior?  Is there a way to fix the ``mocksshy`` script above?

Version info (all on Debian linux 7.1, Python 2.7.3, kernel 3.2.0)...

    (py27_sshmock)[mpenning@tsunami ~]$ pip freeze
    MockSSH==1.4.1
    Twisted==15.0.0
    argparse==1.2.1
    astor==0.4.1
    ecdsa==0.13
    graphite-web==0.9.10
    hy==0.10.1
    paramiko==1.15.2
    pyasn1==0.1.7
    pycrypto==2.6.1
    rply==0.7.3
    wsgiref==0.1.2
    zope.interface==4.1.2
    (py27_sshmock)[mpenning@tsunami ~]$

**Comment by ncouture** [comment]
H

**Comment by ncouture** [comment]
Hi @mpenning 

I have tested argument validation using the mock.hy example and it works at least for command of type "output", which is what you are using.

Have a look at https://github.com/ncouture/MockSSH/blob/master/examples/mock.hy and see if you a

**Comment by ncouture** [comment]
self ~ $ ssh -p2222 testuser@0
testuser@0's password: 
Permission denied, please try again.
testuser@0's password: 
hostname>ls
MockSSH: supported usage: ls -1
hostname>ls -1 2 3 4
MockSSH: supported usage: ls -1
hostname>ls -1
bin/
README.txt
hostname>
```

**Comment by ncouture** [comment]
I
