### ISSUE TITLE
Question: How to run server that does not require password?

### ISSUE THREAD

**Issue by skamsie** [ncouture/MockSSH#20]
Hey, good stuff, but is there a way to run this mock server to emulate one that does not require a password? Where you can just do: `ssh admin@127.0.0.1 -p` and then you're in?

**Comment by ncouture** [comment]
@skamsie there's an open issue (#14) that details a step-by-step implementation for public key authentication in MockSSH. Using ssh keys can allow you to login without requiring a password.

As always, PRs are welcome!
